import './globals.css';
import type { Metadata } from 'next';
import { Roboto_Mono } from 'next/font/google';
import React from 'react';
import Navbar from "@/components/NavBar";

const robotoMono = Roboto_Mono({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'MdoeTech',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={`flex-1 ${robotoMono.className}`}>
        <div className="flex">
            <Navbar/>
            <main className="flex-1 flex flex-col m-10">
                {children}
            </main>
        </div>
        </body>
        </html>
    );
}
